version: 2
project_name: iptv

before:
  hooks:
    - go mod tidy

builds:
  - binary: iptv
    main: ./cmd/iptv/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats:
        - "zip"
    builds_info:
      group: root
      owner: root
    files:
      - config.yml
      - src: "logos/*.png"
        dst: logos
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^style:"
      - "^test:"
      - "^chore:"