version: 2
project_name: iptv

before:
  hooks:
    - go mod tidy

builds:
  - binary: iptv
    main: ./cmd/iptv/main.go
    env:
      - CGO_ENABLED=0
    goos:
     # - windows
     # - darwin
      - linux
    #  - freebsd
    goarch:
      - amd64
      - arm
      - arm64
     # - mips
    #  - mipsle
     # - mips64
     # - mips64le
    goarm:
     # - '5'
     # - '6'
      - '7'
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.REPO_OWNER }}/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.REPO_OWNER }}/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile
    use: buildx  # 明确使用 buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64,linux/arm/v7"
      - "--push"  # 添加 push 标志
    goos: linux
    goarch: amd64
    extra_files:
      - config.yml
      - logos/

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats:
        - "zip"
    builds_info:
      group: root
      owner: root
    files:
      - config.yml
      - src: "logos/*.png"
        dst: logos
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^style:"
      - "^test:"
      - "^chore:"
