name: Release and Publish Docker

on:
  push:
    tags:
      - "v*"
  repository_dispatch:
  workflow_dispatch:
    inputs:
      build_version:
        description: '版本号'
        required: true
        default: 'v1.0.0'

env:
  DOCKER_HUB_REPO: your-dockerhub-username/your-repo-name  # 修改为你的 Docker Hub 仓库
  DOCKER_IMAGE_TAG: ${{ github.ref_name }}                 # 使用 Git 标签作为镜像标签

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      # 运行 GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      # 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          provenance: false
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/iptv-tool:${{ env.MAJOR_VERSION }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/iptv-tool:${{ env.MINOR_VERSION }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/iptv-tool:${{ env.BUILD_VERSION }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/iptv-tool:${{ env.TAG_VERSION }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/iptv-tool:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
