name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      build_version:
        description: '版本号 (格式: v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: build --clean --snapshot
        env:
          GORELEASER_CURRENT_TAG: ${{ github.event.inputs.build_version || github.ref_name }}

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       - name: Set up build args
        run: |
          echo "MAJOR_VERSION=${GITHUB_REF_NAME%%.*}" >> $GITHUB_ENV
          echo "MINOR_VERSION=${GITHUB_REF_NAME%.*}" >> $GITHUB_ENV
          echo "BUILD_VERSION=${{ github.event.inputs.build_version }}" >> $GITHUB_ENV
          echo "TAG_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_EVENT_INPUTS_BUILD_VERSION#v}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/iptv:${{ env.BUILD_VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/iptv:latest
          build-args: |
            INTERVAL=24h
            PORT=8088
            URL=http://192.168.3.1:4022
